@startuml
!pragma layout smetana

left to right direction

actor Bruger as u

rectangle StreamFlix {

  usecase "User Create" as UC1
  usecase "Log ind" as UC2

  usecase "Søg efter film" as UC3
  usecase "Søg efter serie" as UC4
  usecase "Søg efter kategori" as UC5
  usecase "Se sete film/serier" as UC6
  usecase "Se gemte film/serier" as UC7

  usecase "Afspil film" as UC8
  usecase "Gem film til seeliste" as UC9
  usecase "Slet film fra seeliste" as UC10

  usecase "Afspil episode" as UC11
  usecase "Vælg sæson" as UC12
  usecase "Vælg episode" as UC13
  usecase "Gem serie til seeliste" as UC14
  usecase "Slet serie fra seeliste" as UC15

  usecase "Menu" as UC16
  usecase "Log ud" as UC17
  usecase "Start" as UC18

}

' Brugeren starter disse selv
u --> UC18
UC18 --> UC1
UC18 --> UC2
UC2 --> UC16
UC1 --> UC2
UC16 --> UC3
UC16 --> UC4
UC16 --> UC5
UC16 --> UC6
UC16 --> UC7
UC4 --> UC12
UC4 --> UC13
UC3 --> UC9
UC7 --> UC10
UC12 --> UC11
UC4 --> UC14
UC7 --> UC15
UC3 --> UC8

' Knapper man altid kan tilgås
UC17 --> UC18
UC16 --> UC17


}



@enduml